# Generated by Django 5.2.8 on 2026-01-02 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('profile_image_url', models.URLField(max_length=500)),
                ('headline', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('roast_body', models.TextField()),
                ('dating_life', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
